/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jstockfish_Position */

#ifndef _Included_jstockfish_Position
#define _Included_jstockfish_Position
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jstockfish_Position
 * Method:    whiteScores
 * Signature: (ZLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jstockfish_Position_whiteScores
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     jstockfish_Position
 * Method:    isLegal
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jstockfish_Position_isLegal
  (JNIEnv *, jclass, jboolean, jstring, jstring);

/*
 * Class:     jstockfish_Position
 * Method:    fen
 * Signature: (ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jstockfish_Position_fen
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     jstockfish_Position
 * Method:    ordinalState
 * Signature: (ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jstockfish_Position_ordinalState
  (JNIEnv *, jclass, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
