/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jstockfish_Uci */

#ifndef _Included_jstockfish_Uci
#define _Included_jstockfish_Uci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jstockfish_Uci
 * Method:    uci
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jstockfish_Uci_uci
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    setOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jstockfish_Uci_setOption
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     jstockfish_Uci
 * Method:    newGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jstockfish_Uci_newGame
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    position
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jstockfish_Uci_position
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jstockfish_Uci
 * Method:    go
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jstockfish_Uci_go
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jstockfish_Uci
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jstockfish_Uci_stop
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    ponderHit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jstockfish_Uci_ponderHit
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jstockfish_Uci_d
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    flip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jstockfish_Uci_flip
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    eval
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jstockfish_Uci_eval
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    whiteScores
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jstockfish_Uci_whiteScores
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    isLegal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jstockfish_Uci_isLegal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jstockfish_Uci
 * Method:    fen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jstockfish_Uci_fen
  (JNIEnv *, jclass);

/*
 * Class:     jstockfish_Uci
 * Method:    ordinalState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jstockfish_Uci_ordinalState
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
